# Generated by Django 6.0.5 on 2026-05-21 10:50

import applications.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(default=applications.models._generate_tracking_number, editable=False, max_length=20, unique=True)),
                ('applicant_name', models.CharField(max_length=200)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('company_name', models.CharField(max_length=200)),
                ('application_type', models.CharField(choices=[('recordation', 'Recordation'), ('renewal', 'Renewal'), ('change_of_ownership', 'Change of Ownership'), ('change_of_name', 'Change of Name'), ('discontinuation', 'Discontinuation')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('need_more_information', 'Need More Information'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=32)),
                ('reviewer_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='application_status_1508e0_idx'), models.Index(fields=['-created_at'], name='application_created_b96b4a_idx')],
            },
        ),
    ]
